name = "near-me"
compatibility_date = "2024-01-01"
pages_build_output_dir = "./dist"

[[d1_databases]]
binding = "DB"
database_name = "nearme-db"
database_id = "86879c31-0686-4532-a66c-f310b89d7a27"
preview_database_id = "86879c31-0686-4532-a66c-f310b89d7a27"
